name: ci
on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      TEST_TAG: afansuri/docker-react:test
      LATEST_TAG: afansuri/docker-react:latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build base image 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: false
          tags: ${{ env.TEST_TAG }}
      -
        name: Run test suite
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.TEST_TAG }}
          run: docker run -e CI=true ${{ env.TEST_TAG }} npm run test
